/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculatron;

import java.awt.Color;

/**
 *
 * @author Ran
 */
public class cal extends javax.swing.JFrame {
 int  xmouse;
 int  ymouse;

 double num3;
 double num4;
 double num1;
 double num2;
 double result;
 String sign;
 String enter;
    /**
     * Creates new form cal
     */
    public cal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        r2 = new javax.swing.JTextField();
        r1 = new javax.swing.JTextField();
        j1 = new javax.swing.JButton();
        j2 = new javax.swing.JButton();
        j3 = new javax.swing.JButton();
        j4 = new javax.swing.JButton();
        j5 = new javax.swing.JButton();
        j6 = new javax.swing.JButton();
        j7 = new javax.swing.JButton();
        j8 = new javax.swing.JButton();
        j9 = new javax.swing.JButton();
        add = new javax.swing.JButton();
        sub = new javax.swing.JButton();
        multi = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        j0 = new javax.swing.JButton();
        jdot = new javax.swing.JButton();
        equal = new javax.swing.JButton();
        round = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        rai = new javax.swing.JButton();
        square = new javax.swing.JButton();
        reci = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        cube = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        back = new javax.swing.JButton();
        close = new javax.swing.JButton();
        darg = new javax.swing.JLabel();
        cos = new javax.swing.JButton();
        sin = new javax.swing.JButton();
        tan = new javax.swing.JButton();
        log = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        color = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(150, 150));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        r2.setEditable(false);
        r2.setBackground(new java.awt.Color(255, 255, 255));
        r2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        r2.setForeground(new java.awt.Color(0, 0, 0));
        r2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        r2.setBorder(null);
        r2.setCaretColor(new java.awt.Color(255, 255, 255));
        r2.setOpaque(false);
        getContentPane().add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 390, 40));

        r1.setEditable(false);
        r1.setBackground(new java.awt.Color(255, 255, 255));
        r1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        r1.setForeground(new java.awt.Color(0, 0, 0));
        r1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        r1.setBorder(null);
        getContentPane().add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 390, 40));

        j1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        j1.setForeground(java.awt.Color.white);
        j1.setText("1");
        j1.setBorder(null);
        j1.setBorderPainted(false);
        j1.setContentAreaFilled(false);
        j1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                j1MouseMoved(evt);
            }
        });
        j1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                j1MousePressed(evt);
            }
        });
        j1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1ActionPerformed(evt);
            }
        });
        getContentPane().add(j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 132, 60, 50));

        j2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        j2.setForeground(java.awt.Color.white);
        j2.setText("2");
        j2.setBorder(null);
        j2.setBorderPainted(false);
        j2.setContentAreaFilled(false);
        j2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                j2MouseMoved(evt);
            }
        });
        j2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                j2MousePressed(evt);
            }
        });
        j2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2ActionPerformed(evt);
            }
        });
        getContentPane().add(j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 132, 60, 50));

        j3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        j3.setForeground(java.awt.Color.white);
        j3.setText("3");
        j3.setBorder(null);
        j3.setBorderPainted(false);
        j3.setContentAreaFilled(false);
        j3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                j3MouseMoved(evt);
            }
        });
        j3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                j3MousePressed(evt);
            }
        });
        j3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j3ActionPerformed(evt);
            }
        });
        getContentPane().add(j3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 132, 60, 50));

        j4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        j4.setForeground(java.awt.Color.white);
        j4.setText("4");
        j4.setBorder(null);
        j4.setBorderPainted(false);
        j4.setContentAreaFilled(false);
        j4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                j4MouseMoved(evt);
            }
        });
        j4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j4MouseClicked(evt);
            }
        });
        j4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j4ActionPerformed(evt);
            }
        });
        getContentPane().add(j4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 60, 50));

        j5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        j5.setForeground(java.awt.Color.white);
        j5.setText("5");
        j5.setBorder(null);
        j5.setBorderPainted(false);
        j5.setContentAreaFilled(false);
        j5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                j5MouseMoved(evt);
            }
        });
        j5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j5ActionPerformed(evt);
            }
        });
        getContentPane().add(j5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 60, 50));

        j6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        j6.setForeground(java.awt.Color.white);
        j6.setText("6");
        j6.setBorder(null);
        j6.setBorderPainted(false);
        j6.setContentAreaFilled(false);
        j6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                j6MouseMoved(evt);
            }
        });
        j6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j6ActionPerformed(evt);
            }
        });
        getContentPane().add(j6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 60, 50));

        j7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        j7.setForeground(java.awt.Color.white);
        j7.setText("7");
        j7.setBorder(null);
        j7.setBorderPainted(false);
        j7.setContentAreaFilled(false);
        j7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                j7MouseMoved(evt);
            }
        });
        j7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j7ActionPerformed(evt);
            }
        });
        getContentPane().add(j7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 60, 50));

        j8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        j8.setForeground(java.awt.Color.white);
        j8.setText("8");
        j8.setBorder(null);
        j8.setBorderPainted(false);
        j8.setContentAreaFilled(false);
        j8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                j8MouseMoved(evt);
            }
        });
        j8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j8ActionPerformed(evt);
            }
        });
        getContentPane().add(j8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 60, 50));

        j9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        j9.setForeground(java.awt.Color.white);
        j9.setText("9");
        j9.setBorder(null);
        j9.setBorderPainted(false);
        j9.setContentAreaFilled(false);
        j9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                j9MouseMoved(evt);
            }
        });
        j9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j9ActionPerformed(evt);
            }
        });
        getContentPane().add(j9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 60, 50));

        add.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        add.setForeground(java.awt.Color.white);
        add.setText("+");
        add.setBorder(null);
        add.setBorderPainted(false);
        add.setContentAreaFilled(false);
        add.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                addMouseMoved(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 50, 50));

        sub.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        sub.setForeground(java.awt.Color.white);
        sub.setText("-");
        sub.setBorder(null);
        sub.setBorderPainted(false);
        sub.setContentAreaFilled(false);
        sub.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                subMouseMoved(evt);
            }
        });
        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActionPerformed(evt);
            }
        });
        getContentPane().add(sub, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 60, 50));

        multi.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        multi.setForeground(java.awt.Color.white);
        multi.setText("*");
        multi.setBorder(null);
        multi.setBorderPainted(false);
        multi.setContentAreaFilled(false);
        multi.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                multiMouseMoved(evt);
            }
        });
        multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiActionPerformed(evt);
            }
        });
        getContentPane().add(multi, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 50, 40));

        divide.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        divide.setForeground(java.awt.Color.white);
        divide.setText("/");
        divide.setBorder(null);
        divide.setBorderPainted(false);
        divide.setContentAreaFilled(false);
        divide.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                divideMouseMoved(evt);
            }
        });
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });
        getContentPane().add(divide, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 60, 40));

        j0.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        j0.setForeground(java.awt.Color.white);
        j0.setText("0");
        j0.setBorder(null);
        j0.setBorderPainted(false);
        j0.setContentAreaFilled(false);
        j0.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                j0MouseMoved(evt);
            }
        });
        j0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j0ActionPerformed(evt);
            }
        });
        getContentPane().add(j0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 60, 40));

        jdot.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jdot.setForeground(java.awt.Color.white);
        jdot.setText(".");
        jdot.setBorder(null);
        jdot.setBorderPainted(false);
        jdot.setContentAreaFilled(false);
        jdot.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jdotMouseMoved(evt);
            }
        });
        jdot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdotActionPerformed(evt);
            }
        });
        getContentPane().add(jdot, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 60, 40));

        equal.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        equal.setForeground(java.awt.Color.white);
        equal.setText("=");
        equal.setBorder(null);
        equal.setBorderPainted(false);
        equal.setContentAreaFilled(false);
        equal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                equalMouseMoved(evt);
            }
        });
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });
        getContentPane().add(equal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 210, 50));

        round.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        round.setForeground(java.awt.Color.white);
        round.setText("R");
        round.setBorder(null);
        round.setBorderPainted(false);
        round.setContentAreaFilled(false);
        round.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                roundMouseMoved(evt);
            }
        });
        round.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundActionPerformed(evt);
            }
        });
        getContentPane().add(round, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 60, 40));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("n");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 40, 20));

        rai.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        rai.setForeground(java.awt.Color.white);
        rai.setText("X");
        rai.setBorder(null);
        rai.setBorderPainted(false);
        rai.setContentAreaFilled(false);
        rai.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                raiMouseMoved(evt);
            }
        });
        rai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raiActionPerformed(evt);
            }
        });
        getContentPane().add(rai, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 60, 40));

        square.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        square.setForeground(new java.awt.Color(255, 255, 255));
        square.setText("X");
        square.setBorder(null);
        square.setBorderPainted(false);
        square.setContentAreaFilled(false);
        square.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                squareMouseMoved(evt);
            }
        });
        square.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squareActionPerformed(evt);
            }
        });
        getContentPane().add(square, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 60, 50));

        reci.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        reci.setForeground(java.awt.Color.white);
        reci.setText("1/x");
        reci.setBorder(null);
        reci.setBorderPainted(false);
        reci.setContentAreaFilled(false);
        reci.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                reciMouseMoved(evt);
            }
        });
        reci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reciActionPerformed(evt);
            }
        });
        getContentPane().add(reci, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 60, 50));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("3");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 30, -1));

        jButton10.setText("2");
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 40, -1));

        cube.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        cube.setForeground(java.awt.Color.white);
        cube.setText("X");
        cube.setBorder(null);
        cube.setBorderPainted(false);
        cube.setContentAreaFilled(false);
        cube.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cubeMouseMoved(evt);
            }
        });
        cube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cubeActionPerformed(evt);
            }
        });
        getContentPane().add(cube, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 60, 50));

        clear.setBorder(null);
        clear.setBorderPainted(false);
        clear.setContentAreaFilled(false);
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 60, 50));

        back.setBorder(null);
        back.setBorderPainted(false);
        back.setContentAreaFilled(false);
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 130, 50, 50));

        close.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText("X");
        close.setBorder(null);
        close.setBorderPainted(false);
        close.setContentAreaFilled(false);
        close.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                closeMouseMoved(evt);
            }
        });
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 0, 20, -1));

        darg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dargMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                dargMouseMoved(evt);
            }
        });
        darg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dargMousePressed(evt);
            }
        });
        getContentPane().add(darg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 40));

        cos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cos.setForeground(new java.awt.Color(255, 255, 255));
        cos.setText("Cos X");
        cos.setBorder(null);
        cos.setBorderPainted(false);
        cos.setContentAreaFilled(false);
        cos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cosMouseMoved(evt);
            }
        });
        cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosActionPerformed(evt);
            }
        });
        getContentPane().add(cos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 452, 60, 50));

        sin.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        sin.setForeground(new java.awt.Color(255, 255, 255));
        sin.setText("Sin X");
        sin.setBorder(null);
        sin.setBorderPainted(false);
        sin.setContentAreaFilled(false);
        sin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                sinMouseMoved(evt);
            }
        });
        sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinActionPerformed(evt);
            }
        });
        getContentPane().add(sin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 452, 60, 50));

        tan.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tan.setForeground(new java.awt.Color(255, 255, 255));
        tan.setText("TanX");
        tan.setBorder(null);
        tan.setBorderPainted(false);
        tan.setContentAreaFilled(false);
        tan.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tanMouseMoved(evt);
            }
        });
        tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanActionPerformed(evt);
            }
        });
        getContentPane().add(tan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 452, 60, 50));

        log.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        log.setForeground(new java.awt.Color(255, 255, 255));
        log.setText("Log");
        log.setBorder(null);
        log.setBorderPainted(false);
        log.setContentAreaFilled(false);
        log.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                logMouseMoved(evt);
            }
        });
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });
        getContentPane().add(log, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 450, 60, 50));

        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton5MouseMoved(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 20, 10));

        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 30, 20));

        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton4MouseMoved(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 30, 20));

        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton1MouseMoved(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, 20, 20));

        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton2MouseMoved(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 20, 20));

        color.setBorder(null);
        color.setBorderPainted(false);
        color.setContentAreaFilled(false);
        color.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        color.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                colorMouseMoved(evt);
            }
        });
        color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorActionPerformed(evt);
            }
        });
        getContentPane().add(color, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 80, 70));

        background.setForeground(new java.awt.Color(0, 153, 153));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculatron/1.png"))); // NOI18N
        background.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        background.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                backgroundMouseMoved(evt);
            }
        });
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dargMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dargMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xmouse    , y - ymouse);
    }//GEN-LAST:event_dargMouseDragged

    private void dargMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dargMousePressed
        // TODO add your handling code here:
        xmouse = evt.getX();
        ymouse = evt.getY();
    }//GEN-LAST:event_dargMousePressed

    private void dargMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dargMouseMoved
        // TODO add your handling code here:
        close.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_dargMouseMoved

    private void j3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j3ActionPerformed
        // TODO add your handling code here:
        enter = r1.getText()  + j3.getText();
        r1.setText(enter);
    }//GEN-LAST:event_j3ActionPerformed

    private void j5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j5ActionPerformed
        // TODO add your handling code here:
         enter = r1.getText()  + j5.getText();
         r1.setText(enter);
    }//GEN-LAST:event_j5ActionPerformed

    private void jdotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdotActionPerformed
        // TODO add your handling code here:
       
            
        enter = r1.getText()  + jdot.getText();
        r1.setText(enter);
    }//GEN-LAST:event_jdotActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        
        
        System.exit(0);
    }//GEN-LAST:event_closeActionPerformed

    private void closeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseMoved
        // TODO add your handling code here:
        close.setForeground(new java.awt.Color(255, 0, 0));
    }//GEN-LAST:event_closeMouseMoved

    private void j1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j1MouseMoved
        // TODO add your handling code here:
        j1.setForeground(Color.yellow);
    }//GEN-LAST:event_j1MouseMoved

    private void j2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j2MouseMoved
        // TODO add your handling code here:
        j2.setForeground(Color.yellow);
    }//GEN-LAST:event_j2MouseMoved

    private void j3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j3MouseMoved
        // TODO add your handling code here:
        j3.setForeground(Color.yellow);
    }//GEN-LAST:event_j3MouseMoved

    private void j4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j4MouseMoved
        // TODO add your handling code here:
        j4.setForeground(Color.yellow);
    }//GEN-LAST:event_j4MouseMoved

    private void j5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j5MouseMoved
        // TODO add your handling code here:
        j5.setForeground(Color.yellow);
    }//GEN-LAST:event_j5MouseMoved

    private void j6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j6MouseMoved
        // TODO add your handling code here:
        j6.setForeground(Color.yellow);
    }//GEN-LAST:event_j6MouseMoved

    private void addMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseMoved
        // TODO add your handling code here:
        add.setForeground(Color.yellow);
    }//GEN-LAST:event_addMouseMoved

    private void subMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subMouseMoved
        // TODO add your handling code here:
        sub.setForeground(Color.yellow);
    }//GEN-LAST:event_subMouseMoved

    private void j7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j7MouseMoved
        // TODO add your handling code here:
        j7.setForeground(Color.yellow);
    }//GEN-LAST:event_j7MouseMoved

    private void j8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j8MouseMoved
        // TODO add your handling code here:
        j8.setForeground(Color.yellow);
    }//GEN-LAST:event_j8MouseMoved

    private void j9MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j9MouseMoved
        // TODO add your handling code here:
        j9.setForeground(Color.yellow);
    }//GEN-LAST:event_j9MouseMoved

    private void divideMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divideMouseMoved
        // TODO add your handling code here:
        divide.setForeground(Color.yellow);
    }//GEN-LAST:event_divideMouseMoved

    private void j0MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j0MouseMoved
        // TODO add your handling code here:
        j0.setForeground(Color.yellow);
    }//GEN-LAST:event_j0MouseMoved

    private void jdotMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdotMouseMoved
        // TODO add your handling code here:
        jdot.setForeground(Color.yellow);
    }//GEN-LAST:event_jdotMouseMoved

    private void roundMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundMouseMoved
        // TODO add your handling code here:
        round.setForeground(Color.yellow);
    }//GEN-LAST:event_roundMouseMoved

    private void raiMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raiMouseMoved
        // TODO add your handling code here:
        rai.setForeground(Color.yellow);
    }//GEN-LAST:event_raiMouseMoved

    private void reciMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reciMouseMoved
        // TODO add your handling code here:
        reci.setForeground(Color.yellow);
    }//GEN-LAST:event_reciMouseMoved

    private void squareMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_squareMouseMoved
        // TODO add your handling code here:
        square.setForeground(Color.yellow);
    }//GEN-LAST:event_squareMouseMoved

    private void cubeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cubeMouseMoved
        // TODO add your handling code here:
        cube.setForeground(Color.yellow);
    }//GEN-LAST:event_cubeMouseMoved

    private void equalMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equalMouseMoved
        // TODO add your handling code here:
        equal.setForeground(Color.yellow);
    }//GEN-LAST:event_equalMouseMoved

    private void multiMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiMouseMoved
        // TODO add your handling code here:
        multi.setForeground(Color.yellow);
    }//GEN-LAST:event_multiMouseMoved

    private void j1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1ActionPerformed
        // TODO add your handling code here:
         enter = r1.getText()  + j1.getText();
        r1.setText(enter);
    }//GEN-LAST:event_j1ActionPerformed

    private void j2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2ActionPerformed
        // TODO add your handling code here:
        enter = r1.getText()  + j2.getText();
        r1.setText(enter);
    }//GEN-LAST:event_j2ActionPerformed

    private void j4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j4ActionPerformed
        // TODO add your handling code here:
        enter = r1.getText()  + j4.getText();
        r1.setText(enter);
    }//GEN-LAST:event_j4ActionPerformed

    private void j6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j6ActionPerformed
        // TODO add your handling code here:
      enter = r1.getText()  + j6.getText();
        r1.setText(enter);
    }//GEN-LAST:event_j6ActionPerformed

    private void j7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j7ActionPerformed
        // TODO add your handling code here:
         enter = r1.getText()  + j7.getText();
        r1.setText(enter);
    }//GEN-LAST:event_j7ActionPerformed

    private void j8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j8ActionPerformed
        // TODO add your handling code here:
        enter = r1.getText()  + j8.getText();
        r1.setText(enter);
    }//GEN-LAST:event_j8ActionPerformed

    private void j9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j9ActionPerformed
        // TODO add your handling code here:
         enter = r1.getText()  + j9.getText();
         r1.setText(enter);
    }//GEN-LAST:event_j9ActionPerformed

    private void j0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j0ActionPerformed
        // TODO add your handling code here:
        enter = r1.getText()  + j0.getText();
        r1.setText(enter);
    }//GEN-LAST:event_j0ActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
       // TODO add your handling code here:
       
        
        num1 = Double.parseDouble(r1.getText());
        r2.setText(r1.getText() + "+" + r2.getText());
        r1.setText("");
        sign = "+";
        
    }//GEN-LAST:event_addActionPerformed

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed
        // TODO add your handling code here:
        String answer ;
        num2 = Double.parseDouble(r1.getText());
        
        if("+".equals(sign))
        {   result = num1 + num2 ;
            r2.setText(r2.getText()+ r1.getText());
            answer = String.format("%.0f", result);
            r1.setText(answer);
            r2.setText("");
            }
        if("-".equals(sign))
        {   result = num1-num2;
            r2.setText(r2.getText()+ r1.getText());
            answer = String.format("%.0f", result);
            r1.setText(answer);
            r2.setText("");
        }
        if("*".equals(sign))
        { result = num1*num2;
            r2.setText(r2.getText()+ r1.getText());
            r1.setText(Double.toString(result));
            answer = String.format("%.0f", result);
            r1.setText(answer);
            r2.setText("");
        }
        if("/".equals(sign))
        { result = num1-num2;
            r2.setText(r2.getText()+ r1.getText());
            r1.setText(Double.toString(result));
            answer = String.format("%.0f", result);
            r1.setText(answer);
            r2.setText("");
        }
       
        if("@".equals(sign))
        { 
          result = num1*num1*num1;
          r1.setText(Double.toString(result));
          answer = String.format("%.0f", result);
            r1.setText(answer);
            r2.setText("");        
        }
        if("#".equals(sign))
        { 
            result = 1/num1;
            r1.setText(Double.toString(result));
            answer = String.format("%.0f", result);
            r1.setText(answer);
            r2.setText("");
           
        }
        if("$".equals(sign))
        { 
          result = Math.pow(num1,num2) ;
          answer = String.format("%.0f", result);
          r1.setText("Raise to Power =" + answer );
        }
    }//GEN-LAST:event_equalActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        r1.setText("");
        r2.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        r1.setText("");
    }//GEN-LAST:event_backActionPerformed

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(r1.getText());
        r2.setText(r1.getText() + "-" + r2.getText());
        r1.setText("");
        sign = "-";
    }//GEN-LAST:event_subActionPerformed

    private void multiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(r1.getText());
        
        {r2.setText(r1.getText() + "*" + r2.getText());
        r1.setText("");
        sign = "*";}
    }//GEN-LAST:event_multiActionPerformed

    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(r1.getText());
        r2.setText(r1.getText() + "/" + r2.getText());
        r1.setText("");
        sign = "/";
    }//GEN-LAST:event_divideActionPerformed

    private void squareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squareActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(r1.getText());
        r2.setText(r1.getText() + "/" + r2.getText());
        r1.setText("");
        sign = "/";
       
    }//GEN-LAST:event_squareActionPerformed

    private void cubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cubeActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(r1.getText());
        r2.setText("cube of " + r1.getText() );
        r1.setText(r1.getText());
        sign = "@";
    }//GEN-LAST:event_cubeActionPerformed

    private void reciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reciActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(r1.getText());
        r2.setText("Reciprocal of " + r1.getText() );
        r1.setText(r1.getText());
        sign = "#";
    }//GEN-LAST:event_reciActionPerformed

    private void roundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundActionPerformed
        // TODO add your handling code here:
        double number,rounded;
        number = Double.parseDouble(r1.getText());
        rounded = Math.round(number);
        r1.setText(Double.toString(rounded));
    }//GEN-LAST:event_roundActionPerformed

    private void j1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j1MouseClicked
        // TODO add your handling code here:
        j1.setForeground(Color.green);
    }//GEN-LAST:event_j1MouseClicked

    private void j1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j1MousePressed
        // TODO add your handling code here:
        j1.setForeground(Color.red);
    }//GEN-LAST:event_j1MousePressed

    private void j2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j2MouseClicked
        // TODO add your handling code here:
        j2.setForeground(Color.green);
    }//GEN-LAST:event_j2MouseClicked

    private void j2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j2MousePressed
        // TODO add your handling code here:
        j2.setForeground(Color.orange);
    }//GEN-LAST:event_j2MousePressed

    private void j3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j3MouseClicked
        // TODO add your handling code here:
        j3.setForeground(Color.green);
    }//GEN-LAST:event_j3MouseClicked

    private void j3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j3MousePressed
        // TODO add your handling code here:
      j3.setForeground(Color.black);
    }//GEN-LAST:event_j3MousePressed

    private void raiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raiActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(r1.getText());
        r1.setText("");
        r2.setText("Know Enter The Power");
        sign = "$";
        
    }//GEN-LAST:event_raiActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(r1.getText());
        result = Math.log10(num1);
        r2.setText("log "+ (r1.getText()));
        r1.setText(Double.toString(result));
    }//GEN-LAST:event_logActionPerformed

    private void cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(r1.getText());
        result = Math.cos(num1);
        r2.setText("Cos"+ (r1.getText()));
        r1.setText(Double.toString(result));
        
    }//GEN-LAST:event_cosActionPerformed

    private void sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(r1.getText());
        result = Math.sin(num1);
        r2.setText("sin "+ (r1.getText()));
        r1.setText(Double.toString(result));
    }//GEN-LAST:event_sinActionPerformed

    private void tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(r1.getText());
        result = Math.tan(num1);
        r2.setText("Tan "+ (r1.getText()));
        r1.setText(Double.toString(result));
    }//GEN-LAST:event_tanActionPerformed

    private void colorMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorMouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_colorMouseMoved

    private void backgroundMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMouseMoved
        // TODO add your handling code here:
        j1.setForeground(Color.WHITE);
        j2.setForeground(Color.WHITE);
        j3.setForeground(Color.WHITE);
        j4.setForeground(Color.WHITE);
        j5.setForeground(Color.WHITE);
        j6.setForeground(Color.WHITE);
        j7.setForeground(Color.WHITE);
        j8.setForeground(Color.WHITE);
        j9.setForeground(Color.WHITE);
        sub.setForeground(Color.WHITE);
        add.setForeground(Color.WHITE);
        jdot.setForeground(Color.WHITE);
        multi.setForeground(Color.WHITE);
        sin.setForeground(Color.WHITE);
        divide.setForeground(Color.WHITE);
        reci.setForeground(Color.WHITE);
        square.setForeground(Color.WHITE);
        round.setForeground(Color.WHITE);
        cube.setForeground(Color.WHITE);
        cos.setForeground(Color.WHITE);
        tan.setForeground(Color.WHITE);
        
        
        
        color.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        
    }//GEN-LAST:event_backgroundMouseMoved

 @SuppressWarnings("empty-statement")
    private void colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorActionPerformed
        // TODO add your handling code here:
   r1.setText("");
   r2.setText("");
                  
    }//GEN-LAST:event_colorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculatron/3.png")));
        r1.setText("");
        r2.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculatron/4.png")));
        r1.setText("");
        r2.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculatron/2.png")));
        r1.setText("");
        r2.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculatron/5.png")));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cosMouseMoved
        // TODO add your handling code here:
        cos.setForeground(Color.red);
    }//GEN-LAST:event_cosMouseMoved

    private void sinMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sinMouseMoved
        // TODO add your handling code here:
        sin.setForeground(Color.red);
    }//GEN-LAST:event_sinMouseMoved

    private void tanMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tanMouseMoved
        // TODO add your handling code here:
        tan.setForeground(Color.red);
    }//GEN-LAST:event_tanMouseMoved

    private void logMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logMouseMoved
        // TODO add your handling code here:
        log.setForeground(Color.red);
    }//GEN-LAST:event_logMouseMoved

    private void j4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_j4MouseClicked

    private void jButton5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseMoved
        // TODO add your handling code here:
        color.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculatron/next.png")));
        r2.setText("It Comes In Color");
        r1.setText("Click On Different Color In Triangles");
    }//GEN-LAST:event_jButton5MouseMoved

    private void jButton4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseMoved
        // TODO add your handling code here:
        r1.setText("");
        r2.setText("");
    }//GEN-LAST:event_jButton4MouseMoved

    private void jButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseMoved
        // TODO add your handling code here:
        r1.setText("");
        r2.setText("");
    }//GEN-LAST:event_jButton1MouseMoved

    private void jButton2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseMoved
        // TODO add your handling code here:
        r1.setText("");
        r2.setText("");
    }//GEN-LAST:event_jButton2MouseMoved
                                
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JLabel background;
    private javax.swing.JButton clear;
    private javax.swing.JButton close;
    private javax.swing.JButton color;
    private javax.swing.JButton cos;
    private javax.swing.JButton cube;
    private javax.swing.JLabel darg;
    private javax.swing.JButton divide;
    private javax.swing.JButton equal;
    private javax.swing.JButton j0;
    private javax.swing.JButton j1;
    private javax.swing.JButton j2;
    private javax.swing.JButton j3;
    private javax.swing.JButton j4;
    private javax.swing.JButton j5;
    private javax.swing.JButton j6;
    private javax.swing.JButton j7;
    private javax.swing.JButton j8;
    private javax.swing.JButton j9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jdot;
    private javax.swing.JButton log;
    private javax.swing.JButton multi;
    private javax.swing.JTextField r1;
    private javax.swing.JTextField r2;
    private javax.swing.JButton rai;
    private javax.swing.JButton reci;
    private javax.swing.JButton round;
    private javax.swing.JButton sin;
    private javax.swing.JButton square;
    private javax.swing.JButton sub;
    private javax.swing.JButton tan;
    // End of variables declaration//GEN-END:variables
}
